version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: dbconsopredict
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network
  
  api:
    image: eelias78/img_api:latest
    container_name: img_api_from_compose
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: pwd
      DB_NAME: dbconsopredict
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    networks:
      - my-network

  batch:
    image: eelias78/img_batch:latest
    container_name: img_batch_from_compose
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: pwd
      DB_NAME: dbconsopredict
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "8080:80"
    networks:
      - my-network

  mysql-client:
    image: mysql:latest
    command: ["tail", "-f", "/dev/null"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
