name: CI on Push
on: push
env:
  dockerhub_id: eelias78
  dockerhub_repository: img_api
  
jobs:
  
  build-push-api:
    name: Build and push image api and batch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        cd src/api
        docker image build . --no-cache=false -t img_api:latest
        docker tag img_api:latest eelias78/img_api:latest
        cd ../batch
        docker image build . --no-cache=false -t img_batch:latest
        docker tag img_batch:latest eelias78/img_batch:latest
        docker login -u eelias78 -p Phil@ma73
        docker push eelias78/img_api:latest
        docker push eelias78/img_batch:latest